### ISSUE TITLE
Switch syntax definition format from JSON to YAML

### ISSUE THREAD

**Issue by mkldon** [shakeelmohamed/sublime-splunk-conf-highlighting#20]
JSON syntax definitions seems to be deprecated by package dev:
https://github.com/SublimeText/PackageDev#syntax-definition-development
http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html
Also regexps look much better in YAML.

**Comment by shakeelmohamed** [comment]
Thanks for the suggestion @mkldon!
