### ISSUE TITLE
Make setting values optional so following settings are highlighted

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/sublime-splunk-conf-highlighting#23]
In the following example, the entire `foo3 = bar2` line won't be highlighted because the `foo2 =` line ends in whitespace.

```
[default]
foo = bar
foo2 =
foo3 = bar2
```

![image](https://cloud.githubusercontent.com/assets/1480063/18451445/cf8c99c2-78eb-11e6-8fbe-1aa866b93bc1.png)

**Comment by mkldon** [comment]
Its strange, this example works fine on my setup. Do you use the latest version of the package?  Values also aren't highlighted on your screenshot.

![default](https://cloud.githubusercontent.com/assets/923260/18669790/5f5807e4-7f45-11e6-850a-0ba7ee070ba4.PNG)

**Comment by shakeelmohamed** [comment]
Thanks @mkldon, I was still using a dev build 😭
