### ISSUE TITLE
Add lines prefixed with @ as a comment

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/sublime-splunk-conf-highlighting#26]
The regex for `comment.line` can be modified to begin with `@` or `#`

**Comment by ghost** [comment]
I can help with this!

**Comment by ghost** [comment]
Done @shakeelmohamed Let me know if that is okay!

**Comment by richa-coder** [comment]
Is this issue solved?? Can i help?

**Comment by shakeelmohamed** [comment]
@richa-coder almost, progress is in #27. Feel free to look through my other repos for hacktoberfest issues 🎃

**Comment by ghost** [comment]
I think my changes are good now, let me know!
